spring:
  cloud:
    function:
      definition: producer;processor;consumer
    stream:
      bindings:
        producer-out-0:
          destination: numbers
        processor-in-0:
          destination: numbers
        processor-out-0:
          destination: squares
        consumer-in-0:
          destination: squares