server:
 port: 8081
 
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    
  datasource:
    url: "jdbc:mysql://localhost:3306/udemy"
    username: root
    password: root
    
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
