version: '3'
services:
  kmysql:
    image: 'mysql:8.0.32'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: Password
      MYSQL_ROOT_PASSWORD: Password
    volumes:
      - 'db_data:/var/lib/mysql'

  kapp:
    build: .
    image: spring-boot-app
    container_name: docker-mysql-springboot-demo-app
    depends_on:
     - kmysql
    ports:
      - '8080:8080'
    environment:
      DB_HOST: 'kmysql:3306'
      DB_USER: root
      DB_PASSWORD: Password
      DB_NAME: test
      
volumes:
  db_data: {}
