server:
  port: 8001
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-service

      
  kafka:
    bootstrap-servers:
      - localhost:9092

    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.LongDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      
      
#logging:
#  level:
#    root: error
#    org.springframework.data.mongodb.core.query : debug